<a href="https://colab.research.google.com/github/ZainiRana/MACHINE-LEARNING-PROJECT/blob/main/diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

imports essentials libraries

In [52]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
import numpy as np


loading datasets

In [53]:
data=pd.read_csv('/content/diabetes.csv')

:viewing first 5 datasets value

In [54]:
data.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [55]:
data.shape   #row and columns in datasets

(768, 9)

measuring the data statistical

In [56]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [57]:
data['Outcome'].value_counts()  #check how many possible cases that represent 1

Outcome
0    500
1    268
Name: count, dtype: int64

braking the datasets into data and lebels


In [58]:
fect=['Pregnancies', 'Glucose',	'BloodPressure', 'SkinThickness',	'Insulin', 'BMI',	'DiabetesPedigreeFunction',	'Age'	]
X=data[fect]
y=data.Outcome

checking the value of data and lebels

In [59]:
X


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [60]:
y


0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [61]:
scaler = StandardScaler()

In [62]:
standerized_data=scaler.fit_transform(X)


In [63]:
standerized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [64]:
standerized_data.shape

(768, 8)

In [65]:
X=standerized_data

In [66]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [67]:
Y=y

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3)

In [69]:
X_train

array([[-0.84488505, -0.96691063, -0.05715025, ..., -0.95095236,
         2.01177262,  0.23476686],
       [ 2.12477957,  0.53535234,  0.35643175, ...,  0.15324507,
        -0.15667259,  0.14967911],
       [-1.14185152, -0.40356202, -0.05715025, ..., -0.59557847,
         0.95171097, -0.10558415],
       ...,
       [ 0.63994726, -0.184482  , -0.47073225, ...,  0.2167047 ,
        -0.68519336,  0.57511787],
       [-0.84488505,  0.44146091, -0.78091875, ..., -0.67173002,
         0.6496991 ,  2.44704844],
       [-0.84488505, -0.24707629, -0.26394125, ...,  0.20401277,
         0.21480201, -1.04154944]])

In [70]:
X_test

array([[ 0.04601433, -0.77912776, -0.67752325, ..., -1.42055357,
        -0.39828208, -0.61611067],
       [-1.14185152,  0.09719231, -0.67752325, ..., -1.29363432,
        -0.06002879, -1.04154944],
       [-0.84488505, -0.43485916, -0.05715025, ..., -0.69711387,
        -0.92680285, -0.78628618],
       ...,
       [ 0.63994726, -0.49745345,  0.04624525, ..., -0.15136112,
        -1.05666795,  0.31985461],
       [-1.14185152, -0.12188771, -0.16054575, ..., -0.15136112,
         0.06379607, -0.95646168],
       [-0.54791859, -1.65544783,  0.04624525, ..., -0.88749274,
        -0.86036024, -0.70119842]])

In [71]:
y_test

288    0
465    0
89     0
103    0
15     1
      ..
167    0
301    1
329    0
528    0
520    0
Name: Outcome, Length: 231, dtype: int64

In [72]:
y_train

434    0
36     0
202    0
97     0
692    0
      ..
92     0
515    1
664    1
456    0
255    1
Name: Outcome, Length: 537, dtype: int64

In [73]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [74]:
from sklearn.svm import SVC

In [75]:
model = SVC(kernel='rbf')

In [76]:
model.fit(X_train,y_train)

SVC()

In [77]:
y_prediction = model.predict(X_test)

In [78]:
y_prediction

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [79]:
model.score(X_test,y_test)

0.7532467532467533

In [80]:
model.score(X_train,y_train)

0.8286778398510242

In [81]:
input_data=(6,148,72,35,0,33.6,0.627,50)
data_as_numpy = np.asarray(input_data)
reshaped_data = data_as_numpy.reshape(1,-1)
std_data = scaler.transform(reshaped_data)
std_data
prediction = model.predict(std_data)
prediction

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1])

In [82]:
if (prediction[0]==0):
  print('the patient is no diabaties')
else:
  print('the patient is  diabaties')

the patient is  diabaties


In [83]:
import pickle

In [84]:
filename = "trained_model.sav"

In [85]:
pickle.dump(model, open(filename, 'wb'))

In [86]:
#load the model


In [87]:
loaded_model = pickle.load(open('trained_model.sav', 'rb'))

In [88]:
input_data=(6,148,72,35,0,33.6,0.627,50)
data_as_numpy = np.asarray(input_data)
reshaped_data = data_as_numpy.reshape(1,-1)
std_data = scaler.transform(reshaped_data)
std_data
prediction = loaded_model.predict(std_data)
print(prediction)
if (prediction[0]==0):
  print('the patient is no diabaties')
else:
  print('the patient is  diabaties')

[1]
the patient is  diabaties


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
