In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import numpy as np


In [4]:
data=pd.read_csv('/content/heart.csv')

In [5]:
data.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
data.shape

(303, 14)

In [7]:
data.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [8]:
data['target'].value_counts()  #check how many possible cases that represent 1

target
1    165
0    138
Name: count, dtype: int64

In [9]:
fect=['age',	'sex',	'cp',	'trestbps',	'chol',	'fbs',	'restecg',	'thalach',	'exang',	'oldpeak',	'slope',	'ca',	'thal'	]
X=data[fect]
Y=data.target

In [10]:
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [11]:
Y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [12]:
scaler = StandardScaler()

In [13]:
standerized_data=scaler.fit_transform(X)

In [14]:
standerized_data

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -2.27457861,
        -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.47415758, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ..., -0.64911323,
         1.24459328,  1.12302895],
       [ 0.29046364,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221,  1.12302895],
       [ 0.29046364, -1.46841752,  0.03203122, ..., -0.64911323,
         0.26508221, -0.51292188]])

In [15]:
X=standerized_data

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3)

In [17]:
X_train

array([[-1.1432911 ,  0.68100522,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188],
       [ 1.28306308, -1.46841752,  1.97312292, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.1432911 ,  0.68100522,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.39335191, -1.46841752,  1.00257707, ...,  0.97635214,
         0.26508221, -0.51292188],
       [-1.69473524,  0.68100522, -0.93851463, ..., -0.64911323,
        -0.71442887,  1.12302895],
       [ 0.06988599, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188]])

In [18]:
X_test

array([[-0.37126932, -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188],
       [-0.04040284,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221, -0.51292188],
       [-0.04040284, -1.46841752,  0.03203122, ...,  0.97635214,
         0.26508221, -0.51292188],
       ...,
       [-2.13589054,  0.68100522, -0.93851463, ...,  0.97635214,
        -0.71442887,  1.12302895],
       [ 0.9521966 , -1.46841752,  1.00257707, ...,  0.97635214,
        -0.71442887, -0.51292188],
       [ 1.17277425, -1.46841752,  1.00257707, ...,  0.97635214,
         0.26508221, -0.51292188]])

In [19]:
y_train

148    1
17     1
21     1
182    0
289    0
      ..
41     1
125    1
127    1
212    0
161    1
Name: target, Length: 212, dtype: int64

In [20]:
X

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -2.27457861,
        -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.47415758, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ..., -0.64911323,
         1.24459328,  1.12302895],
       [ 0.29046364,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221,  1.12302895],
       [ 0.29046364, -1.46841752,  0.03203122, ..., -0.64911323,
         0.26508221, -0.51292188]])

In [21]:
y_test

140    1
264    0
93     1
184    0
45     1
      ..
111    1
67     1
239    0
54     1
28     1
Name: target, Length: 91, dtype: int64

In [22]:
model = LogisticRegression(max_iter=5000)

In [23]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=5000)

In [24]:
y_prediction = model.predict(X_test)

In [25]:
y_prediction

array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1])

In [26]:
model.score(X_train,y_train)

0.8632075471698113

In [27]:
model.score(X_test,y_test)

0.8241758241758241

In [28]:
input_data=(63,1,3,145,233,1,0,150,0,2.3,0,0,1)
data_as_numpy = np.asarray(input_data)
reshaped_data = data_as_numpy.reshape(1,-1)
std_data = scaler.transform(reshaped_data)
std_data
prediction = model.predict(std_data)
prediction

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1])

In [39]:
if (prediction[0]==0):
  print('clear report')
else:
  print('Our test have shown that you have a heart condition')


Our test have shown that you have a heart condition


In [40]:
import pickle

In [41]:
filename = "trained_model.sav"


In [42]:
pickle.dump(model, open(filename, 'wb'))

In [43]:
input_data=(63,1,3,145,233,1,0,150,0,2.3,0,0,1)
data_as_numpy = np.asarray(input_data)
reshaped_data = data_as_numpy.reshape(1,-1)
std_data = scaler.transform(reshaped_data)
std_data
prediction = model.predict(std_data)
print (prediction)
if (prediction[0]==0):
  print('clear report')
else:
  print('Our test have shown that you have a heart condition')


[1]
Our test have shown that you have a heart condition


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
